### ISSUE TITLE
Implements setting module

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#10]
The person assigned to this issue will implements all functions in the `settings` module.

**Comment by DavidVn64** [comment]
I am working on this module at this moment, to be fair I also finished it but I can't figure out how to test my functions, I changed the main to do so but it doesn't compile. This is the message:
`Messages de l'assembleur:
Erreur fatale: ne peut créer build/main.o: Aucun fichier ou dossier de ce type
Makefile:24 : la recette pour la cible « build/main.o » a échouée
make: *** [build/main.o] Erreur 1
`

**Comment by Kagamihime** [comment]
You have to create the directory `build`

**Comment by GaelleMarais** [comment]
Actually I can't compile either.

> gcc: error: ./build/vilian: Aucun fichier ou dossier de ce type
> Makefile:6 : la recette pour la cible « vilian » a échouée
> make: *** [vilian] Erreur 1

I have the directory `build` 
Am I supposed to create the file `vilain `? 
(Also I just noticed there is a typo,` vilian `instead of` vilain` but that's not the problem here)
