### ISSUE TITLE
Need explication in io_text

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#104]
Hi @DavidVn64 
In the function `load_file` in the module `io_text.c`, can you write comments to explain the different cases where the function returns NULL please ?
I'm working on the `main.c` and when I try to open a file with this function it returns NULL, but there isn't any comments in this code so I don't know why.

**Comment by GaelleMarais** [comment]
When I try to open a file I enter int the condition
` if (insert_char(res, c, i, j) == -1) `
with values  `i=1 ` and `j=0`
and i don't understand why this case returns a NULL buffer ?
Obviously the buffer is empty for now so you can't write anything on the line 1 because it doesn't exist

**Comment by Kagamihime** [comment]
Maybe it's because the file you are trying to open doesn't exist? Or is not readable?

**Comment by GaelleMarais** [comment]
I guess the case where the file doesn't exit is the first `if` but it's not here that the problem occurs

**Comment by Kagamihime** [comment]
@GaelleMarais try this `int i = 0;` instead of `int i = 1;`

**Comment by GaelleMarais** [comment]
I tried it and it doesn't work either.
I don't really understand what this test is supposed to check

**Comment by GaelleMarais** [comment]
Alright this creates the buffer but lines are not in the correct order

**Comment by GaelleMarais** [comment]
I will create an issue about this other problem
