### ISSUE TITLE
Implements cursor module

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#11]
The person assigned to this issue will implements all functions in the `cursor` module.

**Comment by DavidVn64** [comment]
So, do I need to implement the movement of the cursor (with the keyboard) in the buffer in this module ?

**Comment by Kagamihime** [comment]
We've already talked about it: this module is just about storing the position of the cursor and the view, so you don't implement what you've said.

**Comment by GaelleMarais** [comment]
I would like to implements this module because I need it now for the ui and it's not very interesting to code (Also it's quite simple).
Is that okey for you @DavidVn64  ?

**Comment by Kagamihime** [comment]
I think it's better for you to implement it right away, so I reassign it to you ^^

**Comment by DavidVn64** [comment]
Sorry I didn’t check the issue, I am currently busy at work. I will do it don’t worry, we still have plenty of time to do it.

**Comment by DavidVn64** [comment]
It will be done tomorrow

**Comment by DavidVn64** [comment]
Whatever ok then.
