### ISSUE TITLE
Implement auto save and recovery file

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#114]

**Comment by DavidVn64** [comment]
Can you tell me what do you mean by "recovery file"  please ?

**Comment by DavidVn64** [comment]
@Kagamihime Can you help me please about the function pthread_create please ? I know how to use it in a single file with another function, but I need to use it to call a function in the io_text module

**Comment by Kagamihime** [comment]
Sorry, I have no idea whether you can do that or not ^^'

**Comment by DavidVn64** [comment]
Or I could just implement the function auto_save_buffer_thread in main.c but I think this is a bad way to do ?

**Comment by Kagamihime** [comment]
Maybe you can create a new function in io_text that would launch the thread, in io_text.c and add it in io_text.h, so that you call it from main

**Comment by DavidVn64** [comment]
Oh well like you said, it compiles ! I don't know if it works tho
