### ISSUE TITLE
Improve return values of functions in 'settings' and 'io_text' module

### ISSUE THREAD

**Issue by DavidVn64** [Kagamihime/VIlain#117]
To be accorded to the C programming convention that 0 means false and other values means true, and so, to make the code clearer and more usable, we need to change the return values of functions in these modules.

**Comment by GaelleMarais** [comment]
When you will do it don't forget to change the parts of the code where these functions are called otherwise the program will not work correctly.

**Comment by Kagamihime** [comment]
In fact, you should not do that unless the functions are called is_something and are supposed to return a boolean. Whereas function that are supposed to do something like saving a the buffer in a file, they return 0 if they didn't encoutered any errors and -1 if they did. That's a convention in C (and other lowlevel languages) to return 0 for a normal exit and -1 when there is an error.

All the functions in the buffer have these return values

**Comment by Kagamihime** [comment]
The only functions that would need this modification would be "is_current_shortcut" and "valid_config" (that should be renamed "is_valid_config" btw)

**Comment by GaelleMarais** [comment]
@Kagamihime 
Since I am the one who implemented `is_current_shortcut` it already return `0` for false and `1` for true

**Comment by Kagamihime** [comment]
And the "save" function should have an int returned so that it returns -1 if it can't write in the config file and 0 if the configuration was successfully saved ^^

**Comment by Kagamihime** [comment]
@GaelleMarais Okay!
A good way to know that a function is supposed to return a "boolean" is to name it with is_ at the beginning. Other wise, the function is expected to return the usual 0 for success and -1 for failure. I am repeating myself but it's just to be sure that this distinction is clear and that you understand why it is often done like this even if it is not obvious @DavidVn64

**Comment by DavidVn64** [comment]
Oh can you open this issue back please ? I forgot to change the return value of 'save'
