### ISSUE TITLE
Wrong arguments in UML

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#14]
Hi, there is something wrong in the UML: in the` buffer` module we have the argument` str: char*` in the functions `delete_line` and `delete_text `but these functions should have the same arguments as the `get_*` ones.
However I can't fix it because it seems that the UML.dia is not the last version of our UML: when I open it on dia there's still the `menu_bar` module that whe decided to delete.
@DavidVn64 Can you please correct this ?
Thank you

**Comment by GaelleMarais** [comment]
I noticed some other problems, in the `settings` module this time, about the setters.
The functions `set_save_shortcut` and `set_load_shortcut`  take an `int` argument but the getters `get_save_shortcut` and `get_load_shortcut` return a `char*`. Moreover, the other setters take a `char*` argument so I think we should change that for the two setters I just mentioned. 
Also, there is no argument to set the value in `set_toogle_shortcut` : the `char*` is missing there too. 

Sorry if it looks like I'm too strict but I think it's important to have the most accurate UML possible ^^

**Comment by Kagamihime** [comment]
Oh yes, we should have `void set_x_shortcut(char *)` for all setters and `char *get_x_shortcut()` for all getters, as short-cuts will be represented via strings. 

No, it's okay. I should have waited to get home and double check before merging...

**Comment by DavidVn64** [comment]
This is corrected, also you will notice in my update that I changed the position of the variable sets in the function set_line_wrapping since the pointer on the actual struct must be the first argument.
This is awkward, I will push both pdf and .dia files again with the updates to make sure you can correct it yourself next time :)

**Comment by DavidVn64** [comment]
I committed accidentally mentioning 
    Closes https://github.com/Kagamihime/VIlain/issues/140
instead of 
    Closes https://github.com/Kagamihime/VIlain/issues/14
I don't know how to change that, please tell me !

**Comment by Kagamihime** [comment]
You just need to amend your commit and correct the commit message ;)

**Comment by DavidVn64** [comment]
Can you tell me how to amend a commit that is not the last one please ? Thanks !
