### ISSUE TITLE
Explain how to use the coala.sh script

### ISSUE THREAD

**Issue by Kagamihime** [Kagamihime/VIlain#15]
I forgot to explain in the contributing guidelines how to use the script I made for coala.

**Comment by GaelleMarais** [comment]
When I use any of these commands I always get the same response : 

>  ./coala.sh: 3: ./coala.sh: [[: not found
> ./coala.sh: 16: ./coala.sh: [[: not found
> ./coala.sh: 23: ./coala.sh: [[: not found
> Help:
> install    - Install coala in the project's root
> run        - Run coala if it is already installed
> clean      - Remove coala and the python environment from the project's root

**Comment by Kagamihime** [comment]
Oh I get it now...
Try to change the first line of the script so that there is `/bin/bash` instead of `/bin/sh` and tell me if it works, please.

**Comment by GaelleMarais** [comment]
Yes it works thanks a lot

**Comment by Kagamihime** [comment]
This issue wasn't about the bug you've mentioned but something else.
I will make a PR for the fix shortly ^^

**Comment by GaelleMarais** [comment]
I thought you finished explaining how to use the script sorry

**Comment by Kagamihime** [comment]
Oh, my bad! I didn't see that you merged my PR. Sorry...
