### ISSUE TITLE
Need help for Makefile

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#19]
I'm trying to do the makefile but I really can't figure out what I'm doing wrong 
I followed several tutorials to make it work but everytime I get the same error.
Here is what I wrote : 

```
CC = gcc
CFLAGS = -Wall
COMPILE = $(CC) $(CFLAGS)

build/buffer.o: ./src/buffer.c ./include/buffer.h
	$(COMPILE) $< -o $@

build/cursor.o: ./src/cursor.c ./include/cursor.h
	$(COMPILE) $< -o $@

build/io_text.o: ./src/io_text.c ./include/io_text.h
	$(COMPILE) $< -o $@

build/settings.o: ./src/settings.c ./include/settings.h
	$(COMPILE) $< -o $@

build/ui.o: ./src/ui.c ./include/ui.h
	$(COMPILE) $< -o $@

build/main.o: ./src/main.c
	$(COMPILE) $< -o $@

all : ./build/main.o ./build/cursor.o ./build/buffer.o ./build/io_text.o ./build/ui.o ./build/settings.o
	$(CC) $^ -o ./build/$@

clean:
	rm -f ./build/*.o
```

and here is the error on the terminal when I enter `$make all`

> gcc build/main.o build/cursor.o build/buffer.o build/io_text.o build/ui.o build/settings.o -o ./build/main
> /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o : Dans la fonction « _start » :
> (.text+0x20) : référence indéfinie vers « main »
> collect2: error: ld returned 1 exit status
> Makefile:24 : la recette pour la cible « main » a échouée
> make: *** [main] Erreur 1

@Kagamihime  If you know how to help me please ^^

**Comment by Kagamihime** [comment]
You have to add `-c` to `COMPILE` (because you are just compiling and not calling the linker).

By the way, can you add `-std=c11` to `CFLAGS`, please?

Otherwise, your Makefile looks good!

**Comment by GaelleMarais** [comment]
Alright I added those two things but I still get the same error :/

**Comment by GaelleMarais** [comment]
Oh okay I was a bit confused with the `main` function but it works now I think

**Comment by Kagamihime** [comment]
Oh great!
