### ISSUE TITLE
Design and UML diagram

### ISSUE THREAD

**Issue by Kagamihime** [Kagamihime/VIlain#2]
We will discuss here the details about the design of this project.

This issue will be closed when there will be an UML diagram of the modules and their APIs that will be suitable for everyone.
Someone will be assigned to this issue, will write the UML and do a PR. We will be able to start the implementation when this PR will be approved and merged ;)

cc
@GaelleMarais @DavidVnGit

**Comment by DavidVnGit** [comment]
I am currently designing the UML and I'm using an image that can give us a short idea of our goal as a final project.

**Comment by Kagamihime** [comment]
Can you tell us more about what you have done?

**Comment by Kagamihime** [comment]
TODO:
- Rethink the data structure of the buffer (double linked list on the lines)
- Write about the IO module

**Comment by Kagamihime** [comment]
Here is a first proposal for the data structure of the buffer:
- there could be a `BUFFER` struct that would contain a field like `LINE **lines` that would hold a dinamically-sized array of pointers to `LINE`s. There would also be a field like `unsigned int line_count` and other stuffs...
- there could also be a `LINE` struct with a field containing the contents of a line (for instance `char *contents`) and another one for the length of the line (for instance `unsigned int length`). There wouldn't be line returns at the end of `contents` (and it wouldn't be counted in `length`), because a line always end with a line return.

As for the functions:
- `LINE` would have at least functions to read/override/insert/delete a character at a given position.
- `BUFFER` would rely on the functions of `LINE` and add functions to read/modify/insert/delete a certain line.

**Comment by Kagamihime** [comment]
Additionally, I think that we should make a module that would gather helper functions for ncurses: it would be where the ncurses functions would be called, it could be a good abstraction layer and the module would also rely on the functions supplied by the buffer.

As for the text files IO system, it would be nice to have a module dedicated to this. It would mainly supply functions like `BUFFER *load_file(char *path)` and `int save_buffer(BUFFER *buff, char *path)`.

**Comment by DavidVnGit** [comment]
I agree with the fact that our current UML diagram lacks content to correctly represent the structure of our program. We should indeed implement a struct Lines to store the lines of our main buffer.
Though, I think a simple pointer is enough store lines of the buffer, that doesn't make sense to use a double pointer for a struct containing char * already.
We will think about an helping module for ncurses functions later on, since this is typically something we make step by step implementing the project.
I have never used modules to simply manage files in a project, but if you guys think this is necessary, I will had it to the UML.

**Comment by Kagamihime** [comment]
The reason we would need a `LINE **lines` instead of a `LINE *lines` is because it would be way more efficient to do operations for changing the place of a line, insert a line in the middle of the buffer or remove an entire line. For instance, if we want to insert a line, we would have to shift all the lines that come after it and it is faster to shift pointers within an array instead of having to move every `LINE` structs in memory. That's the point of storing an array of pointers to structs instead of storing an array of structs.

And for the ncurses helping module, we can decide right now about what kind of functions we would need. ncurses is a very straightforward library so there is no reason not to do so right now.

Yes an IO module will be necessary because it is a good practice to abstract as much as possible the operations we need the do, it would bloat the code everywhere otherwise. We just have to save and load files from/to a buffer.
We could do the same for settings as we just need to load and save them in a file.

**Comment by DavidVnGit** [comment]
Well I think the way to do such operations is not to use a pointer originally pointing on the struct, but using a temporary pointer to navigate into the line so find the right place to work on.
Yes but I guess it is, for us three, the first application with ncurses; so I don't think we have the required back up to know precisely what operations are being redundant. Personally, I have no idea about what specific functions we need to implement to ease our use of ncurses.
Ok, I added the IO file manage to the UML diagram.

**Comment by DavidVn64** [comment]
Oh and the **unsigned int line_count** was the variable i called **height**. Let me know if you guys want more specific names !

**Comment by Kagamihime** [comment]
It would be almost the something as doing an array of pointers but it would be less practical to write. And it doesn't solve the fact that the lines should be able to be moved easily anyway... The teacher suggested to use a double-linked list to implement this and your proposition would not meet all the requirements that a double-linked list have. An array of pointers to `LINE` structs would be even more efficient and easier to implement than a double-linked list, that's why I'm proposing that and I know why.

For the functions for ncurses, ncurses is all about moving a cursor, reading a keyboard input, writing a character at the cursor's position and styling this input. I am sure that @GaelleMarais or me could come up with some ideas of functions quickly ^^. There could be some functions to print a wrapped line on the screen, print an area of the buffer, print a status bar, update this status bar, highlight a text area (for the selection part of the specification), insert a character, remove a character, open and manipulate a menu to manage the configuration.

We _really_ have to do a design that is as much complete as possible before going further. We will not spend our time on reworking the specification because there were things missing or improvising APIs.
If changes must be done afterwards, it must be minor modifications.

**Comment by Kagamihime** [comment]
Here is a proposition for the `ui` module:

```c
void print_text(BUFFER *buff, unsigned int first_line, unsigned int first_col);
void print_wrapped_text(BUFFER *buff, unsigned int first_line);

void exec_user_action();
void select_text(BUFFER *buff, CURSOR *cursor);

// `str` would enable us to put arbitrary messages inside the status bar
void print_status_bar(CURSOR *cursor, SETTINGS *settings, char *str);

void loading_menu();
void saving_menu();
void settings_menu(SETTINGS *settings);
```

**Comment by Kagamihime** [comment]
And for the `settings` module, in addition to the `save` and `load` functions, we could have `get_*` and `set_*` functions that would act one the following options: `line_wrapping`, `save_shortcut`, `load_shortcut`, `settings_shortcut`, `copy_shortcut`, `cut_shortcut`, `paste_shortcut`, `toogle_selection_shortcut`, and so on... Of course, these functions would all take a `SETTINGS` structure that would be associated with this module.

**Comment by DavidVn64** [comment]
Is it in addition to the current contents of the ui module or is it a whole new design ?

Yes we will use a variable for each option in the settings' file so yes gets and sets functions will be needed. I am ok with specific functions to handle shortcuts since this is usually a little bit tricky to use at start.

If @GaelleMarais is alright with theses propositions, I will had it to the UML.

**Comment by DavidVn64** [comment]
Last time you spoke about 2 kind of coordinates, one to keep track of where the cursor is in the text and, the other to tell what area of the text should be on screen, where do you think we should had the second kind of coordinates ? I think the ui module is right place for these.

**Comment by Kagamihime** [comment]
Yes, it would be a whole new design, as the menu bar will be dropped (for now at least) and the actions made by the user would be executed by `exec_user_action()` (this function would wait for an input and call others functions accordingly), so that we add an abstraction layer because it would be really nice to separate the view and the controller, `exec_user_action()` would be the only controller's function we would need to put in the API.
And `print_wrapped_text()` don't need to have the width passed as an argument as it accessible within ncurses (and we _won't_ use any global variables).

For the coordinates, yes it would be a good idea to have a structure to hold these (in fields like `cursor_x_pos`, `cursor_y_pos`, `first_visible_line` and `first_visible_column`).

**Comment by DavidVn64** [comment]
I just made an update of the UML on the pull request of this issue, following the suggestions made today.

**Comment by GaelleMarais** [comment]
Hi, I have a little question.
Is it normal that in the `buffer` module we have the argument `str: char*` in the functions `delete_line` and `delete_text` ?
I don't understand what they're supposed to mean because we don't need to have the str that we want to delete.

**Comment by Kagamihime** [comment]
It's not normal, indeed ^^': it should have the same arguments as the `get_*` ones.
Please @GaelleMarais , open a new issue about it, so that it will be fixed
