### ISSUE TITLE
Segmentation fault when calling insert_line

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#44]
Sorry but there is still a problem with the function `insert_line(buff,str,int)` when calling it on an empty buffer.
Indeed, the `for` starts at `line_count-1` which is `0-1` and then it tries to put something in `lines[i]` so it is not possible and I get a Segmentation fault when executing.

I'm sorry to ask you to work on this again 
Also, you can copy this in `main.c` to test if your function is working
```
int main void(){
   struct BUFFER *buff;
    buff = new_buffer();
    char *str1= "Hello world";
    int a = insert_line(buff, str1, 0);
    char *str2 = get_line(buff, 0);
    printf("%d  %s", a,  str1);
   return 0;
}
```

**Comment by Kagamihime** [comment]
Sorry, I can't fix it for now, I have to finish my work on the buffer first

**Comment by GaelleMarais** [comment]
Okey not a problem
