### ISSUE TITLE
Finish implementation of the ui

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#63]
To do:
- delete shortcuts that doesn't work. ✔
- print only printable caractere ✘
- utf-8 ✘
- ui.cfg ✔
- add ./files/ with examples ✔
- status bar ✔
- suppr
- select_text when cursor is on the last char of the line
- right & left arrows to move between lines when prec line is full
- size & placement of the menus 
- del last line when scrolly >0 ✔
- clean the code
- delete unnecessary things

**Comment by Kagamihime** [comment]
Just checking in to know how is it going for you with that. Will it be done soon?

**Comment by GaelleMarais** [comment]
Currently working on the shortcuts, but I am more focuses on my exams right now so I will probably push some stuff next week
