### ISSUE TITLE
Remove  `FILE_MAX_LENGTH` and `LINE_MAX_LENGTH` from the module `io_text`

### ISSUE THREAD

**Issue by Kagamihime** [Kagamihime/VIlain#83]
It is not necessary to define such limits as the buffer will automatically grow if the lines/file are very long.

**Comment by DavidVn64** [comment]
Can you explain me again, why is it a LINE ** in the struct BUFFER and not a LINE * please ? I don't get it

**Comment by DavidVn64** [comment]
Well to be honest I only know fgetc/fgets to read a file and I'm pretty sure I need a concrete value LINE_LENGTH_MAX in order to use it, do you know another function more suitable to work with your module BUFFER ?

**Comment by DavidVn64** [comment]
And indeed I've never used FILE_MAX_LENGTH so I need to remove it

**Comment by Kagamihime** [comment]
In this case, you should read the file one character after another (with `getc`) and insert the character you are reading in the buffer with `insert_char`. Of course, you will also need to create an empty line when needed with calls to `insert_line`
