### ISSUE TITLE
Create function get_string in settings.c

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#87]
I need to create a function `string get_string(int a)` to get the key corresponding to an ascii code
For example get_string(19) would return "Ctrl+S"

**Comment by Kagamihime** [comment]
You could also implement it as a helper function within the ui module, couldn't you?

**Comment by DavidVn64** [comment]
Hum isn't it the opposite ? like you want a function to give you the ascii code (so an int) given a String no ?

**Comment by DavidVn64** [comment]
I actually don't know what does mean DC3 as a symbol in the Ascii code, but does it specify clearly that the value of a variable is "ctrl+s" or "ctrl+p" for example ?

**Comment by GaelleMarais** [comment]
Here is the website I used to find the ascii code of keys like "ctrl+something" : 
http://www2.agroparistech.fr/mmip/mc/intdocs/ascii.html
(The last part)

**Comment by Kagamihime** [comment]
@GaelleMarais No, it's okay if you want it to be in the settings module ^^
