### ISSUE TITLE
Start the implementation of the buffer module

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#9]
The person assigned to this issue will implements all functions in the `buffer` module.

**Comment by Kagamihime** [comment]
I think I will take the buffer

**Comment by Kagamihime** [comment]
Notes:
1. I had to change a little bit the API of the buffer: nothing that breaks the other parts of the program, just made some integers unsigned; except for the function `get_line_length` that had an argument missing.
2. I simply did a basic buffer for now: it has a fixed size (but big enough for testing purpose).

**Comment by GaelleMarais** [comment]
Alright thank you
